const CREW=[
 {name:'Cesar',role:'El Rey de la Fiesta',team:'Honorary',icon:'👑',title:'El Rey de la Fiesta',quote:'This weekend is yours. Your crew gathered to celebrate you.'},
 {name:'Daniel',role:'El Padrino',team:'Fortaleza',icon:'🤵',title:'El Padrino',quote:'The one keeping the story moving and the crew together.'},
 {name:'Kevin',role:'Crew',team:'Fortaleza',icon:'🥃'},
 {name:'Gerardo',role:'Crew',team:'Fortaleza',icon:'🌵'},
 {name:'David',role:'Crew',team:'G4',icon:'🔥'},
 {name:'Chucky',role:'Crew',team:'G4',icon:'😂'},
 {name:'Jose',role:'Crew',team:'G4',icon:'🍻'},
 {name:'Arturo',role:'Crew',team:'Centenario',icon:'🏜️'},
 {name:'Frank',role:'Crew',team:'Centenario',icon:'🌙'}
];
const AVATARS=[['agave','🌵','Agave'],['sunset','🌅','Sunset'],['canyon','🏜️','Canyon'],['tequila','🥃','Tequila'],['margarita','🍹','Margarita'],['palm','🌴','Palm'],['taco','🌮','Taco'],['fire','🔥','Campfire'],['gold','👑','Gold']];
const TITLES={planner:['El Águila','A steady leader with sharp instincts.'],party:['El Fuego','The spark that turns a good night legendary.'],foodie:['El Catador','Knows the good stuff and respects the craft.'],explorer:['El Explorador','Always ready for the next adventure.'],chill:['El Compadre','The friend everyone wants around.'],night:['El Nocturno','Built for late nights and unforgettable stories.']};
const SCHEDULE={Thursday:[['3:13 PM','Land at PHX'],['4:15 PM','Arrive at Casa de la Fiesta'],['5:00 PM','Grocery + liquor run'],['7:00 PM','First dinner at the house'],['10:00 PM','Old Town Scottsdale']],Friday:[['Morning','Team Fortaleza breakfast'],['10:00 AM','SXS Desert Adventure'],['Afternoon','Pool recovery'],['Evening','Steak dinner + nightlife']],Saturday:[['Morning','Team G4 breakfast'],['Noon','Pool day + photos'],['Evening','Bachelor dinner'],['Night','VIP night']],Sunday:[['Morning','Team Centenario breakfast'],['Afternoon','Recovery + pool'],['Evening','Awards + final toast'],['Late','Messages to Cesar unlock']],Monday:[['8:00 AM','Pack and clean'],['10:45 AM','Leave Airbnb'],['1:28 PM','Flight home from PHX']]};
const state={tab:'home',profile:load('fiestaProfile'),toast:null};
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}function byId(id){return document.getElementById(id)}
function app(){const a=byId('app');a.innerHTML=`<main class="app fadeIn">${renderTab()}</main>${nav()}${state.toast?`<div class="toast">${state.toast}</div>`:''}`;wire()}
function nav(){return `<nav class="nav">${[['home','🏠','Home'],['passport','🎟️','Passport'],['weekend','📅','Weekend'],['crew','👥','Crew'],['more','☰','More']].map(x=>`<button data-tab="${x[0]}" class="${state.tab===x[0]?'active':''}">${x[1]}<br>${x[2]}</button>`).join('')}</nav>`}
function renderTab(){return ({home:home(),passport:passport(),weekend:weekend(),crew:crew(),more:more()})[state.tab]}
function home(){const p=state.profile;return `<section class="hero"><div class="eyebrow">Scottsdale • July 9–13, 2026</div><h1>One Last Fiesta Before the Siesta</h1><p>Every legend has a role. Every fiesta has a story.</p><div class="pillrow"><span class="pill">👑 Cesar</span><span class="pill">9 Amigos</span><span class="pill">3 Cocina Teams</span></div><button class="btn" data-tab="passport">${p?'Open My Passport':'Begin Your Journey'}</button></section><h2 class="section-title">Command Center</h2><div class="grid"><div class="card"><div class="stat" id="countdown">--</div><div class="muted">until the fiesta</div></div><div class="card"><div class="stat">9</div><div class="muted">crew members</div></div><div class="card"><h3>Next Up</h3><p class="muted">Profile reveal, passport stamp, and crew check-in.</p></div><div class="card"><h3>Casa</h3><p class="muted">Seven Palms North Scottsdale</p></div></div>${p?`<h2 class="section-title">Welcome back, ${p.firstName}</h2><div class="card passport"><div class="person"><div class="photo">${p.avatarIcon}</div><div><div class="role">${p.title}</div><h2>${p.firstName}</h2><p class="muted">${p.team||'Team pending'} • ${p.room||'Room pending'}</p></div></div></div>`:''}`}
function passport(){const p=state.profile;if(!p)return profileForm();return `<h1 class="section-title">My Fiesta Passport</h1><div class="card passport"><div class="person"><div class="photo">${p.photo?`<img src="${p.photo}">`:p.avatarIcon}</div><div><div class="role">${p.title}</div><h2>${p.firstName}${p.nick?` “${p.nick}”`:''}</h2><p class="muted">${p.quote}</p></div></div><hr><p><b>Favorite Drink:</b> ${p.drink}</p><p><b>Favorite Taco:</b> ${p.taco}</p><p><b>Walk-Up Song:</b> ${p.song}</p><p><b>Fun Fact:</b> ${p.fact}</p><p><b>Cocina Team:</b> ${p.team}</p><p><b>Room:</b> ${p.room||'Pending'}</p></div><h2 class="section-title">Passport Stamps</h2><div class="stampgrid">${['Casa Check-in','First Toast','Desert Survivor','Cocina Crew','Bachelor Dinner','Final Toast'].map(s=>`<div class="stamp">${s}</div>`).join('')}</div><button class="btn secondary" id="editProfile">Edit Passport</button><button class="btn ghost" id="clearProfile">Clear My Data</button>`}
function profileForm(){return `<h1 class="section-title">Create Your Fiesta Passport</h1><div class="card"><div class="form"><div class="field"><label>Profile photo</label><input id="photo" type="file" accept="image/*"></div><div class="field"><label>First name</label><select id="firstName">${CREW.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div class="field"><label>Nickname optional</label><input id="nick" placeholder="Example: Big D"></div><div class="field"><label>Favorite drink</label><input id="drink" placeholder="Tequila soda, beer, old fashioned..."></div><div class="field"><label>Favorite taco</label><input id="taco" placeholder="Carne asada, al pastor..."></div><div class="field"><label>Walk-up song</label><input id="song" placeholder="Your entrance music"></div><div class="field"><label>Fun fact</label><textarea id="fact" rows="3"></textarea></div><div class="field"><label>Vacation personality</label><select id="personality"><option value="planner">Planner</option><option value="party">Party Starter</option><option value="foodie">Foodie</option><option value="explorer">Explorer</option><option value="chill">Go With The Flow</option><option value="night">Night Owl</option></select></div><label><b>Choose your avatar frame</b></label><div class="avatars">${AVATARS.map((a,i)=>`<button class="avatarChoice ${i===0?'selected':''}" data-avatar="${a[0]}" data-icon="${a[1]}"><div class="avatarIcon">${a[1]}</div><small>${a[2]}</small></button>`).join('')}</div><button class="btn" id="createProfile">Reveal My Fiesta Title</button></div></div>`}
function weekend(){return `<h1 class="section-title">Weekend Schedule</h1>${Object.entries(SCHEDULE).map(([day,events])=>`<div class="card"><h2>${day}</h2><div class="timeline">${events.map(e=>`<div class="event"><div class="time">${e[0]}</div><div>${e[1]}</div></div>`).join('')}</div></div>`).join('')}`}
function crew(){return `<h1 class="section-title">The Crew</h1><div class="crew">${CREW.map(c=>`<div class="card person ${c.team!=='Honorary'?'team':''}"><div class="photo">${c.icon}</div><div><div class="role">${c.role}</div><h2>${c.name}</h2><p class="muted">${c.team}</p></div></div>`).join('')}</div>`}
function more(){return `<h1 class="section-title">More</h1><div class="card"><h2>Casa de la Fiesta</h2><p>Seven Palms North Scottsdale<br>5617 E Yolantha Street, Scottsdale, AZ</p><p class="muted">Pool • Putting Green • Arcade • Full Kitchen • Backyard Hangout</p></div><div class="card"><h2>Cocina Teams</h2><p><b>Fortaleza:</b> Daniel, Kevin, Gerardo</p><p><b>G4:</b> David, Chucky, Jose</p><p><b>Centenario:</b> Arturo, Frank, Cesar</p></div><div class="card"><h2>Awards</h2><p>🏆 Cocina Champions<br>🍻 Fiesta MVP<br>😂 Funniest Moment<br>📸 Best Photo<br>🌵 Desert Legend</p></div><div class="card"><h2>Memory Book</h2><textarea id="memory" rows="5" placeholder="Write a message to Cesar..."></textarea><button class="btn" id="saveMemory">Save Message</button></div>`}
function wire(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;app()});document.querySelectorAll('.avatarChoice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.avatarChoice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});const cp=byId('createProfile');if(cp)cp.onclick=createProfile;const ep=byId('editProfile');if(ep)ep.onclick=()=>{state.profile=null;app()};const cl=byId('clearProfile');if(cl)cl.onclick=()=>{localStorage.clear();state.profile=null;flash('Local app data cleared.');app()};const sm=byId('saveMemory');if(sm)sm.onclick=()=>{save('fiestaMemory',byId('memory').value);flash('Message saved.')}}
function createProfile(){const crew=CREW.find(c=>c.name===byId('firstName').value);const selected=document.querySelector('.avatarChoice.selected');let title,quote;if(crew.title){title=crew.title;quote=crew.quote}else{[title,quote]=TITLES[byId('personality').value]}const profile={firstName:crew.name,nick:byId('nick').value,drink:byId('drink').value||'Pending',taco:byId('taco').value||'Pending',song:byId('song').value||'Pending',fact:byId('fact').value||'Pending',avatar:selected.dataset.avatar,avatarIcon:selected.dataset.icon,title,quote,team:crew.team,room:'Pending',photo:null};const file=byId('photo').files[0];if(file){const r=new FileReader();r.onload=()=>{profile.photo=r.result;finish(profile)};r.readAsDataURL(file)}else finish(profile)}
function finish(profile){save('fiestaProfile',profile);state.profile=profile;document.body.insertAdjacentHTML('beforeend',`<div class="reveal"><div><div class="eyebrow">Your Fiesta Spirit Has Been Revealed</div><h1>${profile.title}</h1><p>${profile.quote}</p><button class="btn" id="acceptTitle">Accept My Title</button></div></div>`);byId('acceptTitle').onclick=()=>{document.querySelector('.reveal').remove();state.tab='passport';app()}}
function flash(msg){state.toast=msg;setTimeout(()=>{state.toast=null;app()},1600)}
function countdown(){const el=byId('countdown');if(!el)return;const target=new Date('2026-07-09T15:13:00-07:00');const diff=target-new Date();if(diff<=0){el.textContent='Fiesta Time';return}const d=Math.floor(diff/86400000);el.textContent=d+' days'}
setInterval(countdown,1000);app();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');
